### PR TITLE
Modify: update mihawk-xml version in mihawk_defconfig

### PR DESCRIPTION
**Pull request by NicholeWang**
Update MACHINE_XML_VERSION for replacing the MEMD file

Signed-off-by: Nichole Wang Nichole_Wang@wistron.com

### CODE REVIEW

**Comment by NicholeWang** [comment]
Upstream merged: open-power/op-build#3706

**Comment by klauskiwi** [comment]
Ok to test

**Comment by klauskiwi** [comment]
ok to test

**Comment by klauskiwi** [comment]
ok to test

**Comment by klauskiwi** [comment]
@NicholeWang I noted now that you omitted a Signed-off-by line..

Since you'll be pushing this again, can you do it with `git cherry-pick -xs {upstream-commit-id}` so that has the SoB and cherry-pick reference?

Thanks

**Comment by NicholeWang** [comment]
@klauskiwi The cherry-pick commits from upstream are updated.

**Comment by klauskiwi** [comment]
I'll squash the commits into one, but next time you should do it yourself by rebasing on top of the upstream tree you want to merge, and force-pushing

**Pull request merged**
