### PR TITLE
Merge op-build v1.21-rc2, keeping OP910 specific trees.

### PR DESCRIPTION
**Pull request by stewart-ibm**
Merge tag 'v1.21-rc2' into op910
    
    op-build v1.21-rc2
    
    We keep sbe, occ, hostboot and hostboot-binaries, witherspoon-xml
    as they were as these are specific to OP910 branch.
    
    Updated packages (for witherspoon_defconfig):
    
    Package       | Old Version        | New Version
    ------------- | -----------        | -----------
    busybox       | 1.27.1             | 1.27.2
    capp-ucode    | p9-dd2-v2          | p9-dd2-v3
    ethtool       | 4.10               | 4.13
    eudev         | 3.2.2              | 3.2.4
    glibc         | 2.25               | glibc-2.26-73-g4b692dff
    iprutils      | 2.4.14.1           | 2.4.15.1
    kexec-lite    | 86e45a47e8c        | 87d044a895b1
    libflash      | v5.8-123-gc06ed583 | v5.9-166-g70f14f4dd86e
    linux         | 4.13.16            | 4.14.16
    linux-headers | 4.13.16            | 4.14.16
    lvm2          | 2.02.171           | 2.02.173
    mdadm         | 3.3.4              | 4.0
    openpower-pnor| 21d66daff697f8c13f | de0f8e47de145df11a18d0
    petitboot     | v1.6.3             | v1.6.6
    skiboot       | v5.9-240-g08188269 | v5.10-rc3
    util-linux    | 2.30.1             | 2.31
    
    Signed-off-by: Stewart Smith <stewart@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
This also enables us to do nice things like easily merge in kernel bumps from op-build master, like I've done in the second commit in this PR: https://github.com/ibm-op-release/op-build/pull/124/commits/08c34305b51bbf96307ef2394e536480fef4994d

**Comment by stewart-ibm** [comment]
@sannerd @wghoffa any objections to this going in?

**Comment by wghoffa** [comment]
@sannerd - I think you need to look at this from a mustfix perspective. Most of the changes are either P8 config changes, or P9 changes to systems not named witherspoon. I think the few things that are witherspoon related are:

- I see this brings in a few commits from PNOR: https://github.com/open-power/pnor/commits/master - readOnly flag to PNOR partitions/Pnor HDAT addition/ATTR_PERM fix for P8.

- IMA Catalog - Which I think we want?

- Linux Kernel/Skiroot changes.

- FFS changes

I'm fine with it all, just not sure if it's all been approved.

**Comment by stewart-ibm** [comment]
The mustfix process is a mystery to me

**Comment by stewart-ibm** [comment]
Contains skiboot 5.10-rc3, which supersedes https://github.com/ibm-op-release/op-build/pull/142

**Pull request merged**
