### PR TITLE
Modify mihawk config files

### PR DESCRIPTION
**Pull request by chcyjoy**
Update mihawk config to sync up settings from witherspoon.

Signed-off-by: Joy Chu <joy_chu@wistron.com>

### CODE REVIEW

**Comment by HankChang** [comment]
FYR - Looks like this is merged on upstream here:
https://github.com/open-power/op-build/commit/f9c0ed5dbcda581c0693626085a48501822866a9#diff-0286d66c9c4f61b94d904c42603c2fc9

-Hank

**Comment by dcrowell77** [comment]
Looks good to me

**Comment by klauskiwi** [comment]
@chcyjoy Joy, same request as asked in PR #664, can you "git cherry-pick -x -s" and force-push here so that we can have a reference of what commit this pulled from?

Context: in case we rebase this branch with newer op-build later, it should be easier to merge

**Comment by chcyjoy** [comment]
@klauskiwi The commits from upstream are updated.

**Pull request merged**
