### PR TITLE
petitboot: Update to v1.15

### PR DESCRIPTION
**Pull request by rarbab**
This release has fixes for a few issues we've seen on witherspoons in the field.

We can also remove some patches we were carrying on top of v1.13 which are now upstream.

### CODE REVIEW

**Comment by IlyaSmirnov91** [comment]
ok to test

**Comment by IlyaSmirnov91** [comment]
retest this please

**Comment by IlyaSmirnov91** [comment]
retest this please

**Comment by fspbld** [comment]
retest this please

**Comment by fspbld** [comment]
This seems to be failing CI - File "/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-op-releases-1024/CONFIG/witherspoon/OS/redhat-8/build/op-build/output/build/sbe-47abe2a55e6337cebececdb8b57c1d9c238e6d18/src/build/security/securityRegListGen.py", line 64
    print "usage: p9_security_list_gen.py [-h] [-f <security_list_path>] [-0 <output directory] [i] [-d] [-v]\n\
arguments:\n\
-h, --help               show this help message and exit\n\
-f, --file               path to the security list csv file\n\
-o, --output             output directory\n\
-w, --whitelist          print whitelist read from csv\n\
-b, --blacklist          print blacklist read from csv\n\
-g, --greylist           print greylist read from csv\n\
-i, --info               get version info of the security list\n\
-d, --debug              enable debug traces\n\
-v, --verbose            enable verbose traces"
          ^
SyntaxError: Missing parentheses in call to 'print'. Did you mean print("usage: p9_security_list_gen.py [-h] [-f <security_list_path>] [-0 <output directory] [i] [-d] [-v]\n\


I am confused by this because I got the sbe team to update their code to fix these syntax errors when running on RH8.  Perhaps, this is running on an older commit level of op-build?    This PR fixed the sbe syntax errors:  https://github.com/ibm-op-release/op-build/pull/1247 (merged 2 weeks ago)

**Comment by IlyaSmirnov91** [comment]
> This seems to be failing CI - File "/tmp/hostboot-jenkins.swg-devops/jenkins-agent/workspace/Hostboot/OpenPower/GHPR/build-multi-op-releases-1024/CONFIG/witherspoon/OS/redhat-8/build/op-build/output/build/sbe-47abe2a55e6337cebececdb8b57c1d9c238e6d18/src/build/security/securityRegListGen.py", line 64 print "usage: p9_security_list_gen.py [-h] [-f <security_list_path>] [-0 <output directory] [i] [-d] [-v]\n arguments:\n -h, --help show this help message and exit\n -f, --file path to the security list csv file\n -o, --output output directory\n -w, --whitelist print whitelist read from csv\n -b, --blacklist print blacklist read from csv\n -g, --greylist print greylist read from csv\n -i, --info get version info of the security list\n -d, --debug enable debug traces\n -v, --verbose enable verbose traces" ^ SyntaxError: Missing parentheses in call to 'print'. Did you mean print("usage: p9_security_list_gen.py [-h] [-f <security_list_path>] [-0 <output directory] [i] [-d] [-v]\n\
> 
> I am confused by this because I got the sbe team to update their code to fix these syntax errors when running on RH8. Perhaps, this is running on an older commit level of op-build? This PR fixed the sbe syntax errors: #1247 (merged 2 weeks ago)

Yep, @rarbab may need to rebase the commit locally and re-push.

**Comment by rarbab** [comment]
Okay, rebased my branch on current release-op940 to include the sbe fixes.

**Comment by fspbld** [comment]
things are looking better now  :)

**Pull request merged**
