### PR TITLE
petitboot: Include custom cpu ordering patch

### PR DESCRIPTION
**Pull request by sammj**
Include the custom CPU ordering hook from Ben so we can apply this to
only machines using the release-op910 branch.

Signed-off-by: Samuel Mendoza-Jonas <sam@mendozajonas.com>

### CODE REVIEW

**Comment by rosnbrg** [comment]
Here's the motivation for this request. The P9 chips used in CORAL have 22 "good" cores and 2 "bad" cores. Each CORAL node has two such chips. Currently, logical cpu numbers are assigned to physical cpus in purely ascending order. Bad cores are simply skipped. The problem is that cores are not entirely interchangeable. Cores are paired in "chiplets", with each pair sharing an L2/L3. When a single bad core is skipped, two things happen. The partner of the bad core gets an L2/L3 to itself, and subsequent cores are paired in an odd-even pattern rather than an even-odd pattern, up until the next bad core is encountered. Both of these effects can lead to performance anomalies among cores, and the anomalies vary from node to node depending on the location of the bad cores in each chip.

On CORAL we generally reserve one or two cores per P9 chip for system activity. We use the highest numbered cores for this purpose. We've requested this change in logical-to-physical core numbering in order to get the "singleton" cores, if there are any, to be used as the system cores, leaving at least 20 uniformly-paired cores (per chip) for the application. With this change, logical cores 0-19 and 22-41 will have consistent performance across all nodes. There will be some unavoidable variation node-to-node on cores 20-21 and 42-43.

**Comment by sammj** [comment]
CI playing up somewhere:
```
+ cd /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi-op-releases/CONFIG/witherspoon/OS/rhel6.4/build/hostboot
/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi-op-releases/CONFIG/witherspoon/OS/rhel6.4/openpower-ci/build-auto/op-ci-build.sh: line 510: cd: /tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi-op-releases/CONFIG/witherspoon/OS/rhel6.4/build/hostboot: No such file or directory
```

**Comment by sammj** [comment]
Just in case, when I said "CI playing up somewhere" I meant that the CI is broken, not my change. Can someone have a look at this PR please?

**Comment by klauskiwi** [comment]
@rosnbrg can you clarify if this is still a requirement? Please contact me at my ibm e-mail (Klaus Kiwi) if you want to discuss

**Pull request closed without merging**
