### PR TITLE
Op910 merge pre 2.0.11

### PR DESCRIPTION
**Pull request by stewart-ibm**
NOTE: components still left at OP910 versions where applicable.

### CODE REVIEW

**Comment by stewart-ibm** [comment]
@sammj could you check I wasn't insane with my pnor changes here... I'm not convinced I did the right thing in the merge.

**Comment by sammj** [comment]
```
ERROR: Specified input file (/tmp/hostboot-jenkins.swg-devops/jenkins-slave/workspace/Hostboot/OpenPower/GHPR/build-multi-op-releases/CONFIG/witherspoon/OS/rhel6.4/build/op-build/output/host/powerpc64le-buildroot-linux-gnu/sysroot/openpower_pnor_scratch//openpower_pnor_version.bin) for key (VERSION) does not exist
```
You may be right, I'll see what's missing

**Comment by sammj** [comment]
Somehow the openpower-pnor version change has got lost, it should be at least `2e68ed6a605d709e09fe268366565a3f10afec31`: https://github.com/ibm-op-release/op-build/blob/70ec89d8c69c3c0e48cc04ed6e848c06c990332e/openpower/package/openpower-pnor/openpower-pnor.mk#L7

**Comment by stewart-ibm** [comment]
Sam Mendoza-Jonas <notifications@github.com> writes:
> Somehow the openpower-pnor version change has got lost, it should be
> at least `2e68ed6a605d709e09fe268366565a3f10afec31`:
> https://github.com/ibm-op-release/op-build/blob/70ec89d8c69c3c0e48cc04ed6e848c06c990332e/openpower/package/openpower-pnor/openpower-pnor.mk#L7

I messed up the merge, that's how that happens :)

Redoing it :)

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
Stewart Smith <stewart@linux.ibm.com> writes:
> Sam Mendoza-Jonas <notifications@github.com> writes:
>> Somehow the openpower-pnor version change has got lost, it should be
>> at least `2e68ed6a605d709e09fe268366565a3f10afec31`:
>> https://github.com/ibm-op-release/op-build/blob/70ec89d8c69c3c0e48cc04ed6e848c06c990332e/openpower/package/openpower-pnor/openpower-pnor.mk#L7
>
> I messed up the merge, that's how that happens :)
>
> Redoing it :)

I take that back... this whole thing is because we have a fork of pnor
for OP910 as we need to base off a tree pre-hcode building code.

Because the way PNOR images are assembled is just... *terrible*.

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by stewart-ibm** [comment]
Superceded by https://github.com/ibm-op-release/op-build/pull/480 and https://github.com/ibm-op-release/op-build/pull/481

**Pull request closed without merging**
