### PR TITLE
Remove patch folder variable from mihawk_defconfig

### PR DESCRIPTION
**Pull request by chcyjoy**
Modify: remove BR2_GLOBAL_PATCH_DIR from mihawk_defconfig

Signed-off-by: Joy Chu <joy_chu@wistron.com>

### CODE REVIEW

**Comment by chcyjoy** [comment]
Cancel the PR.

**Comment by chcyjoy** [comment]
Reopen this pull request to prevent from pnor build error.
--Joy Chu

**Comment by klauskiwi** [comment]
I'm not sure I understand the reason from removing this variable.. Wouldn't it be innocuous if the directory is simply empty?

How is this being dealt with upstream, have you removed that variable there as well?

**Comment by chcyjoy** [comment]
@klauskiwi I can't keep an empty directory since it follows the desgin of Git.
https://git.wiki.kernel.org/index.php/GitFaq#Can_I_add_empty_directories.3F

I sent the pull request to upstream, too (https://github.com/open-power/op-build/pull/3083).

**Comment by chcyjoy** [comment]
@klauskiwi The pull request in upstream (open-power/op-build#3083) was merged. Would you please help us handle this pull quest?

**Pull request merged**
