### PR TITLE
[OP920] skiboot update

### PR DESCRIPTION
**Pull request by hegdevasant**
Adriana Kobylak (1):
      pflash: Add --skip option for reading

Alexey Kardashevskiy (3):
      npu2: Advertise correct TCE page size
      cpufeatures: Always advertise POWER8NVL as DD2
      hw/phb3/naples: Disable D-states

Andrew Jeffery (49):
      libflash/test: Generate header dependencies for tests
      test-ipmi-hiomap: Add ability to delay some IPMI messages
      test-ipmi-hiomap: Dump unexpected IPMI messages
      test-ipmi-hiomap: Ensure the completion code is set
      test-ipmi-hiomap: Print some information on early
      libflash/ipmi-hiomap: Fix leak of msg in callback
      libflash/ipmi-hiomap: Overhaul error handling
      libflash/ipmi-hiomap: Overhaul event handling
      libflash/ipmi-hiomap: Remove unused close handling
      libflash/ipmi-hiomap: Enforce message size for empty response
      test-ipmi-hiomap: Add protocol-persistent-error test
      test-ipmi-hiomap: Add read-one-block test
      test-ipmi-hiomap: Add read-two-blocks test
      test-ipmi-hiomap: Add event-before-read
      test-ipmi-hiomap: Add event-during-read test
      test-ipmi-hiomap: Add write-one-block test
      test-ipmi-hiomap: Add write-two-blocks test
      test-ipmi-hiomap: Add event-before-write test
      test-ipmi-hiomap: Add event-during-write test
      test-ipmi-hiomap: Add erase-one-block test
      test-ipmi-hiomap: Add erase-two-blocks test
      test-ipmi-hiomap: Add event-before-erase test
      test-ipmi-hiomap: Add event-during-erase
      test-ipmi-hiomap: Add bad-sequence test
      test-ipmi-hiomap: Add action-error test
      test-ipmi-hiomap: Add get-flash-info test
      test-ipmi-hiomap: Add get-info-error test
      test-ipmi-hiomap: Add get-flash-info-error test
      test-ipmi-hiomap: Add create-read-window-error test
      test-ipmi-hiomap: Add create-write-window-error test
      test-ipmi-hiomap: Add mark-dirty-error test
      test-ipmi-hiomap: Add flush-error test
      test-ipmi-hiomap: Add ack-error test
      test-ipmi-hiomap: Add erase-error test
      test-ipmi-hiomap: Add ack-malformed tests
      test-ipmi-hiomap: Add get-info-malformed tests
      test-ipmi-hiomap: Add get-flash-info-malformed tests
      test-ipmi-hiomap: Add create-read-window-malformed tests
      test-ipmi-hiomap: Add create-write-window-malformed tests
      test-ipmi-hiomap: Add mark-dirty-malformed tests
      test-ipmi-hiomap: Add flush-malformed tests
      test-ipmi-hiomap: Add erase-malformed tests
      test-ipmi-hiomap: Add protocol-recovery-failure-ack test
      test-ipmi-hiomap: Add protocol-recovery-failure-get-info test
      test-ipmi-hiomap: Add protocol-recovery-get-flash-info-failure test
      test-ipmi-hiomap: Add read-one-block-twice test
      test-ipmi-hiomap: Add write-one-block-twice test
      test-ipmi-hiomap: Add erase-one-block-twice test
      core/flash: Retry requests as necessary in flash_load_resource()

Deb McLemore (4):
      p9dsu: Fix p9dsu default variant
      p9dsu: Fix p9dsu slot tables
      p9dsu: Fix slot labels for p9dsu2u
      p9dsu: Undo slot label name changes

Frederic Barrat (1):
      i2c: Fix i2c request hang during opal init if timers are not checked

Mahesh Salgaonkar (2):
      Fix hang in pnv_platform_error_reboot path due to TOD failure.
      opal/hmi: Initialize the hmi event with old value of TFMR.

Michael Neuling (1):
      phb4: Generate checkstop on AIB ECC corr/uncorr for DD2.0 parts

Nicholas Piggin (2):
      core/cpu: HID update race
      core/lock: don't set bust_locks on lock error

Oliver O'Halloran (2):
      hw/xscom: Enable sw xstop by default on p9
      pci/iov: Remove skiboot VF tracking

Reza Arbab (1):
      core/lock: Stop drop_my_locks() from always causing abort

Samuel Mendoza-Jonas (2):
      libflash: Restore blocklevel tests
      libflash: Don't merge ECC-protected ranges

Shilpasri G Bhat (2):
      opal-prd: hservice: Enable hservice->wakeup() in BMC
      powercap: occ: Fix the powercapping range allowed for user

Stewart Smith (6):
      skiboot v6.0.13 release notes
      ipmi: Reduce ipmi_queue_msg_sync() polling loop time to 10ms
      skiboot v6.0.14 release notes
      firmware-versions: Add test case for parsing VERSION
      hdata/test: workaround dtc bugs
      skiboot v6.0.17 release notes

Vasant Hegde (21):
      opal-prd: Fix opal-prd crash
      skiboot v6.0.15 release notes
      skiboot v6.0.16 release notes
      hdata: Fix dtc warnings
      core/ipmi: Improve error message
      core/opal: Print PIR value in exit path
      ipmi/power: Fix system reboot issue
      hw/bt: Fix message retry handler
      hw/bt: Add backend interface to disable ipmi message retry option
      hw/bt: Introduce separate list for synchronous messages
      core/ipmi: Add ipmi sync messages to top of the list
      hw/bt: Do not disable ipmi message retry during OPAL boot
      skiboot v6.0.18 release notes
      skiboot v6.0.19 release notes
      core/ipmi: Print correct netfn value
      libflash/ipmi-hiomap: Fix blocks count issue
      test-ipmi-hiomap: Assert if size is zero
      test-ipmi-hiomap: Add write-one-byte test
      test-ipmi-hiomap: Fix lpc-read-success
      test-ipmi-hiomap: Add read-one-byte test
      skiboot v6.0.20 release notes

Signed-off-by: Vasant Hegde <hegdevasant@linux.vnet.ibm.com>

### CODE REVIEW

**Comment by stewart-ibm** [comment]
hrm... I thiought this branch was unused and we just had op-build-2.0.y in open-power/op-build ?

**Comment by hegdevasant** [comment]
> hrm... I thiought this branch was unused and we just had op-build-2.0.y in open-power/op-build ?

I thought all IBM builds happens from here. So do we use upstream 2.0.y for OP920?

-Vasant

**Comment by stewart-ibm** [comment]
hegdevasant <notifications@github.com> writes:
>> hrm... I thiought this branch was unused and we just had op-build-2.0.y in open-power/op-build ?
>
> I thought all IBM builds happens from here. So do we use upstream
> 2.0.y for OP920?

Yes, AFAIK

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by fspbld** [comment]
Correct, ibm-op-release org is used for release-op910 and release-op930. op920 is built from open-power/op-build op-build-2.0.y

**Comment by hegdevasant** [comment]
> Correct, ibm-op-release org is used for release-op910 and release-op930. op920 is built from open-power/op-build op-build-2.0.y

Then why are we having OP920 branches? What's the purpose of those branches? 

-Vasant

**Comment by stewart-ibm** [comment]
hegdevasant <notifications@github.com> writes:
>> Correct, ibm-op-release org is used for release-op910 and release-op930. op920 is built from open-power/op-build op-build-2.0.y
>
> Then why are we having OP920 branches? What's the purpose of those
> branches?

To confuse and complicate things!

-- 
Stewart Smith
OPAL Architect, IBM.

**Comment by hegdevasant** [comment]
Ok then I will close this PR. 
But I think we should cleanup this tree.

-Vasant

**Pull request closed without merging**
